[toolchain]
solana_version = "4.0.1"
anchor_version = "1.1.2"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
