[toolchain]
solana_version = "2.0.19"
anchor_version = "0.30.1-4cdb0ebe8f613f7dbbd5c4b00571139b2517898f"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"