[package]
name = "order-engine-sdk"
version = "0.1.0"
edition.workspace = true

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
solana-sdk = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
