[package]
name = "squads-sdk"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
sha2 = { workspace = true }
solana-compute-budget-interface = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-message = { workspace = true }
solana-pubkey = { workspace = true }
solana-signer = { workspace = true }
solana-transaction = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
solana-rpc-client = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
