[package]
name = "webhook-api"
version = "0.1.0"
edition = "2021"
# edition.workspace = true

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
strum = { version = "0.26.3", features = ["derive"] }
utoipa = { version = "5.3.1", features = ["debug"] }
